server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1024
    min-spare-threads: 30
    accept-count: 5000
  connection-timeout: 1000ms
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
      health:
        show-details: ALWAYS

spring:
  profiles:
    active: dev
  application:
    name: quartjob
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  boot:
    admin:
      client:
        url: http://192.168.163.151:8089
        instance:
          prefer-ip: true


ribbon:
  ReadTimeout: 300000  #请求处理的超时时间
  ConnectTimeout: 300000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或分号隔开
  typeAliasesPackage: com.quartjob.core.**
  configuration:
    #是否开启自动驼峰命名规则（camel case）映射
    map-underscore-to-camel-case: true
    #全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存
    cache-enabled: false
    call-setters-on-nulls: true
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    #MyBatis 自动映射时未知列或未知属性处理策略
    auto-mapping-unknown-column-behavior: none
    # 配置slq打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      #主键类型
      id-type: auto
      #字段验证策略
      field-strategy: NOT_EMPTY
      #数据库大写下划线转换
      capital-mode: true
      #逻辑删除值
      logic-delete-value: 0
      #逻辑不删除值
      logic-not-delete-value: 1

flowable:
  async-executor-activate: false
  database-schema-update: false
